default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        language: system
        entry: make lint
        files: \.py$

      - id: typecheck
        name: Type Check
        language: system
        entry: make typecheck
        files: \.py$

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
