name: "LaTeX Validation Action"
description: "Validates (spell/grammar checks and lints) the LaTeX files of the SSW lectures and exercises"
inputs:
  sample_input:
    description: "Some description"
    required: false # or leave out ot make it required
    default: "Some default value"
  python_version:
    description: "Python version to use"
    required: false
    default: "3.13"
  texlive_version:
    description: "TeX Live version to use"
    required: false
    default: "2024"
  texlive_packages:
    description: "TeX Live packages to install"
    required: false
    default: >-
      scheme-basic
outputs:
  sample_output:
    description: "Sample output"
    value: ${{ steps.dummy.outputs.sample_output }}
runs:
  using: "composite"
  steps:
    # TODO: these first steps are probably also needed in your action as they set up python and use the requirements file from the _action_ repository
    # Create symbolic link for requirements.txt (https://github.com/actions/setup-python/issues/361#issuecomment-2530429607)
    # to work around https://github.com/actions/setup-python/issues/361
    # - name: Create symbolic link for requirements.txt
    #   run: ln -s ${{ github.action_path }}/requirements.txt
    #   shell: bash
    # # install Python
    # - name: Setup Python
    #   uses: actions/setup-python@v4
    #   with:
    #     cache: "pip"
    #     python-version: ${{ inputs.python_version }}

    # - name: Install Python dependencies
    #   working-directory: ${{ github.action_path }}
    #   shell: bash
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install --upgrade setuptools
    #     pip install -r requirements.txt

    # TODO: if you also need texlive, you can use this step
    # # install TeX live + install required dependencies
    # - name: Setup TeX Live
    #   uses: teatimeguest/setup-texlive-action@v3
    #   with:
    #     version: ${{ inputs.texlive_version }}
    #     packages: ${{ inputs.texlive_packages }}

    # just print the input and set a new output
    - name: Dummy
      id: dummy
      shell: bash
      run: |
        echo "Sample input: ${{ inputs.sample_input }}"
        echo "Python version: ${{ inputs.python_version }}"
        echo "TeX Live version: ${{ inputs.texlive_version }}"
        echo "TeX Live packages: ${{ inputs.texlive_packages }}"
        echo "::set-output name=sample_output::Sample output"
