name: Test spelling exercises (dorny)

on:
  workflow_call:
    inputs:
      lint_pr_comment_with_zipped_report:
        description: 'For linting: create PR-comment with chktex-reports packaged as zip'
        required: false
        type: 'boolean'
        default: 'false'
jobs:
  check_ci_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "Start reusable workflow"

      # Get changedtex  files
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: 'json'
          filters: |
            changed:
              - added|modified: '*SS/**/*.tex'
              - added|modified: '*WS/**/*.tex'

      #- name: Print changed files
      - run: |
          echo "Changed Files:"
          echo ${{ steps.filter.outputs.changed_files }}
